// GENERATED FILE — DO NOT EDIT.
// Regenerated by: node android/scripts/extract-theme-fixture.mjs
// Source of truth: design-handoff/playster/project/editorial/theme.jsx
//                  design-handoff/playster/project/editorial/app.jsx (step axes)
// Colors are ARGB longs; rgba() alphas are quantized with round(a * 255),
// matching Compose's Color -> toArgb() 8-bit quantization.
package com.github.jayteealao.playster.ui.editorial

object EditorialThemeFixture {
    data class PaletteFixture(
        val paper: Long,
        val paperDeep: Long,
        val paperEdge: Long,
        val ink: Long,
        val inkSoft: Long,
        val inkFaint: Long,
        val rule: Long,
        val ruleFaint: Long,
        val highlight: Long,
        val dark: Boolean,
    )

    data class AccentFixture(val color: Long, val soft: Long)

    data class FaceFixture(val displayFamily: String, val bodyFamily: String)

    data class RampFixture(
        val fontSize: Double,
        val lineHeight: Double?,
        val letterSpacing: Double?,
        val fontWeight: Int,
    )

    val palettes: Map<String, PaletteFixture> =
        mapOf(
            "cream" to
                PaletteFixture(
                    paper = 0xFFF3EEE4,
                    paperDeep = 0xFFEAE3D2,
                    paperEdge = 0xFFDDD4C0,
                    ink = 0xFF22201A,
                    inkSoft = 0xFF56503F,
                    inkFaint = 0xFF8A8472,
                    rule = 0x2922201A,
                    ruleFaint = 0x1422201A,
                    highlight = 0xFFF3DA7A,
                    dark = false,
                ),
            "vellum" to
                PaletteFixture(
                    paper = 0xFFF7F2E7,
                    paperDeep = 0xFFEFE7D3,
                    paperEdge = 0xFFDDD1B3,
                    ink = 0xFF1A1812,
                    inkSoft = 0xFF5A5340,
                    inkFaint = 0xFF8E8770,
                    rule = 0x291A1812,
                    ruleFaint = 0x141A1812,
                    highlight = 0xFFFFE082,
                    dark = false,
                ),
            "newsprint" to
                PaletteFixture(
                    paper = 0xFFEBE7DF,
                    paperDeep = 0xFFDFD9CC,
                    paperEdge = 0xFFCCC6B6,
                    ink = 0xFF16161A,
                    inkSoft = 0xFF4D4A45,
                    inkFaint = 0xFF807D76,
                    rule = 0x2E16161A,
                    ruleFaint = 0x1416161A,
                    highlight = 0xFFFFF58A,
                    dark = false,
                ),
            "night" to
                PaletteFixture(
                    paper = 0xFF1C1A17,
                    paperDeep = 0xFF15130F,
                    paperEdge = 0xFF272420,
                    ink = 0xFFECE6D6,
                    inkSoft = 0xFFA8A191,
                    inkFaint = 0xFF6A6457,
                    rule = 0x29ECE6D6,
                    ruleFaint = 0x12ECE6D6,
                    highlight = 0x52F8C248,
                    dark = true,
                ),
        )

    val accents: Map<String, AccentFixture> =
        mapOf(
            "oxblood" to AccentFixture(color = 0xFF7A2E1D, soft = 0xFFE9C8B8),
            "forest" to AccentFixture(color = 0xFF2F5A3B, soft = 0xFFCDE0CE),
            "slate" to AccentFixture(color = 0xFF37475A, soft = 0xFFCBD3DC),
            "ink" to AccentFixture(color = 0xFF22201A, soft = 0xFFD8D2C2),
        )

    val faces: Map<String, FaceFixture> =
        mapOf(
            "source" to FaceFixture(displayFamily = "Source Serif 4", bodyFamily = "Source Serif 4"),
            "garamond" to FaceFixture(displayFamily = "EB Garamond", bodyFamily = "EB Garamond"),
            "cormorant" to FaceFixture(displayFamily = "Cormorant Garamond", bodyFamily = "Source Serif 4"),
            "fraunces" to FaceFixture(displayFamily = "Fraunces", bodyFamily = "Source Serif 4"),
        )

    const val SANS_FAMILY: String = "Inter Tight"

    val ramps: Map<String, RampFixture> =
        mapOf(
            "kicker" to RampFixture(fontSize = 9.5, lineHeight = null, letterSpacing = 1.6, fontWeight = 700),
            "appBarKicker" to RampFixture(fontSize = 10.0, lineHeight = null, letterSpacing = 1.6, fontWeight = 600),
            "display" to RampFixture(fontSize = 26.0, lineHeight = 1.05, letterSpacing = -0.4, fontWeight = 400),
            "deck" to RampFixture(fontSize = 12.0, lineHeight = 1.4, letterSpacing = null, fontWeight = 400),
            "body" to RampFixture(fontSize = 13.0, lineHeight = 1.55, letterSpacing = null, fontWeight = 400),
            "dropcap" to RampFixture(fontSize = 44.0, lineHeight = 0.82, letterSpacing = null, fontWeight = 500),
            "pullQuote" to RampFixture(fontSize = 18.0, lineHeight = 1.2, letterSpacing = -0.2, fontWeight = 400),
            "folio" to RampFixture(fontSize = 9.5, lineHeight = null, letterSpacing = 1.4, fontWeight = 600),
            "navLabel" to RampFixture(fontSize = 11.5, lineHeight = null, letterSpacing = 0.2, fontWeight = 700),
        )

    const val NAV_LABEL_INACTIVE_WEIGHT: Int = 500

    val sizeSteps: List<Double> = listOf(0.9, 1.0, 1.1, 1.2)

    val densitySteps: List<Double> = listOf(0.85, 1.0, 1.18)

    /** The mock's ed.s() arithmetic: multiply, then round to 2 decimals. */
    fun edS(
        base: Double,
        step: Double,
    ): Double = Math.round(base * step * 100.0) / 100.0
}
